project_id = "azwiljtrbtaupofwmpzb"

[functions.studio-chat]
verify_jwt = false

[functions.import-product]
verify_jwt = false

[functions.mobile-upload]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.generate-freestyle]
verify_jwt = false

[functions.generate-workflow-preview]
verify_jwt = false

[functions.generate-workflow]
verify_jwt = false

[functions.describe-image]
verify_jwt = false