project_id = "azwiljtrbtaupofwmpzb"

[functions.studio-chat]
verify_jwt = false

[functions.import-product]
verify_jwt = false

[functions.mobile-upload]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.generate-freestyle]
verify_jwt = false

[functions.generate-workflow-preview]
verify_jwt = false

[functions.generate-workflow]
verify_jwt = false

[functions.describe-image]
verify_jwt = false

[functions.create-scene-from-image]
verify_jwt = false

[functions.create-model-from-image]
verify_jwt = false

[functions.analyze-product-image]
verify_jwt = false

[functions.enqueue-generation]
verify_jwt = false

[functions.process-queue]
verify_jwt = false

[functions.generate-tryon]
verify_jwt = false

[functions.generate-product]
verify_jwt = false

[functions.retry-queue]
verify_jwt = false

[functions.generate-scene-previews]
verify_jwt = false
